version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    command: --lower_case_table_names=2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: controlePedidos
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  app:
    image: interface.webapi
    build:
      context: .
      dockerfile: src/Interface.WebApi/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=controlePedidos;User=admin;Password=root;"